### ISSUE TITLE
프론트엔드 UI 수정

### ISSUE THREAD

**Issue by projectjjj** [bestmealever/Thebestmeal#6]
-'결과' 페이지 내 UI 수정
-버튼 디자인 수정
-음식 사진 이미지를 <img src~~ 코드를 div의 background-image 값으로 주는 것으로 변경.
강의에서 이미지를 보여주는 방식이라 적용해봤는데, 검색해보니 스타일을 적용하기가 <img>에 비해 유연하다고 합니다.

참고
https://www.daleseo.com/css-buttons/

**Comment by dlfnek** [comment]
- 전체 페이지, 카드 hover color 및 active color 적용 완료
- 페이지 하단, '다음', '땡기는게 없어요' 등 버튼 병렬 배치 적용 완료
- 페이지 상단, 홈 / 마이페이지 구분 버튼 배치 완료

**Comment by dlfnek** [comment]
1차 프론트엔드 구성 완료
